name: Build All OnePlus Kernels
on:
  workflow_dispatch:
    inputs:
      FILE:
        type: choice
        description: "配置文件"
        required: true
        default: oneplus_ace2_pro_b
        options:
          - oneplus_nord_n30_se_5g_v
          - oneplus_10r_v
          - oneplus_nord_3_v
          - oneplus_ace_v
          - oneplus_ace_race_v
          - oneplus_10_pro_b
          - oneplus_10t_v
          - oneplus_11r_b
          - oneplus_ace2_b
          - oneplus_pad_lite_b
          - oneplus_pad_lite_Canary_b
          - oneplus_pad_mt6983_b
          - oneplus_ace_2v_b
          - oneplus_ace_pro_v
          - oneplus_11_b
          - oneplus_12r_b
          - oneplus_ace2_pro_b
          - oneplus_ace3_b
          - oneplus_open_b
          - oneplus_nord_ce4_b
          - oneplus_12_b
          - oneplus_pad_go_2_b
          - oneplus_nord_ce4_lite_5g_b
          - oneplus_turbo_6v
          - oneplus_nord_4_b
          - oneplus_ace_3v_b
          - oneplus_pad_mt6897_b
          - oneplus_13r_b
          - oneplus_ace3_pro_v
          - oneplus_ace5_b
          - oneplus_pad_pro_b
          - oneplus_pad2_b
          - oneplus_nord_ce5_b
          - oneplus_nord_5_b
          - oneplus_ace5_pro_b
          - oneplus_13_b
          - oneplus_13t_b
          - oneplus_13s_b
          - oneplus_pad_2_pro_b
          - oneplus_pad_3_b
          - oneplus_ace5_race_b
          - oneplus_ace5_ultra_b
          - oneplus_pad2_mt6991_b
          - oneplus_ace_6
          - oneplus_turbo_6
          - oneplus_nord_6
          - oneplus_ace_6t
          - oneplus_ace_6t_Canary
          - oneplus_15r
          - oneplus_15r_Canary
          - oneplus_15
          - oneplus_15_Canary
          - oneplus_15t
          - oneplus_15t_Canary
          - oneplus_pad_3_pro
          - oneplus_pad_3_pro_Canary
          - oneplus_pad_4
          - oneplus_pad_4_Canary
      MANAGER_SOURCE:
        type: choice
        description: "管理器调用方向"
        required: true
        default: MIUIX
        options:
          - MIUIX
          - MIUIX_SPOOF
          - MD3
          - MD3_SPOOF
      SUSFS_CI:
        type: choice
        description: "SUSFS模块下载调用方向"
        required: true
        default: N/A
        options:
          - CI
          - Release
          - N/A
      KPM:
        type: choice
        description: "内核模块实现方式"
        required: true
        default: KPM
        options:
          - KPM
          - KPN
          - N/A
      SUSFS_META:
        type: string
        description: "回退SUSFS(输入哈希或次数或-1关闭)"
        required: false
        default: ""
      DYNAMIC_REPO:
        type: string
        description: "动态清单仓库所有者"
        required: true
        default: "Numbersf"
      BUILD_TIME:
        type: string
        description: "自定义构建时间(输入F使用UTCT或-1关闭)"
        required: false
        default: "Fri Dec 12 11:37:03 UTC 2025"
      KSU_META:
        type: string
        description: "分支名(必填)/自定义版本标识(留空不修改)/回退分支提交哈希版本(留空不修改)"
        required: false
        default: "builtin/Numbersf/"
      LZ4_UPDATE:
        type: boolean
        description: "是否升级LZ4到上游最新？"
        required: true
        default: false
      ZRAM:
        type: string
        description: "ZRAM(0关闭1开启)/算法名/大小"
        required: true
        default: "0/lz4kd/8589934592"
      SUFFIX:
        type: string
        description: "自定义内核后缀(不输入使用RAND_STR或-1关闭)"
        required: false
        default: ""
      SUBLEVEL:
        description: "自定义内核等级欺骗(SUBLEVEL)"
        required: false
        default: ""
      FAST_BUILD:
        type: boolean
        description: "是否启用极速构建？"
        required: true
        default: true
      LSM_BBG:
        type: boolean
        description: "是否启用关键分区写入保护模块(BBG)？"
        required: true
        default: true
      NETFILTER:
        type: boolean
        description: "是否启用网络功能拓展(NETFILTER)？"
        required: true
        default: true
      CCM:
        type: boolean
        description: "是否启用网络拥塞控制与管理机制(BBR+ECN)？"
        required: true
        default: true
      UNICODE_BYPASS:
        type: boolean
        description: "是否添加Unicode不可见字码点绕过读取漏洞修复？"
        required: true
        default: false
      SCHED_HMBIRD:
        type: boolean
        description: "是否添加风驰驱动1.0？"
        required: true
        default: false
      DROID_SPACES:
        type: boolean
        description: "是否添加轻量级Linux容器支持(DroidSpaces)？"
        required: true
        default: false
      RE_KERNEL:
        type: boolean
        description: "是否添加Re-Kernel？"
        required: true
        default: false
      SUSFS_DEV:
        type: boolean
        description: "是否拉取SUSFS-DEV分支？"
        required: true
        default: false
      SPACE_NOCLEAN:
        type: boolean
        description: "是否停用空间清扫？"
        required: true
        default: false
      BUILD_NOCACHE:
        type: boolean
        description: "是否停用此次缓存？"
        required: true
        default: false

permissions:
  contents: write
  actions: read

jobs:
  build:
    uses: ./.github/workflows/build-kernel-reusable.yml
    with:
      FILE: ${{ github.event.inputs.FILE }}
      MANAGER_SOURCE: ${{ github.event.inputs.MANAGER_SOURCE }}
      SUSFS_CI: ${{ github.event.inputs.SUSFS_CI }}
      KPM: ${{ github.event.inputs.KPM }}
      DYNAMIC_REPO: ${{ github.event.inputs.DYNAMIC_REPO }}
      BUILD_TIME: ${{ github.event.inputs.BUILD_TIME }}
      KSU_META: ${{ github.event.inputs.KSU_META }}
      LZ4_UPDATE: ${{ github.event.inputs.LZ4_UPDATE }}
      ZRAM: ${{ github.event.inputs.ZRAM }}
      SUFFIX: ${{ github.event.inputs.SUFFIX }}
      SUBLEVEL: ${{ github.event.inputs.SUBLEVEL }}
      FAST_BUILD: ${{ github.event.inputs.FAST_BUILD }}
      LSM_BBG: ${{ github.event.inputs.LSM_BBG }}
      NETFILTER: ${{ github.event.inputs.NETFILTER }}
      CCM: ${{ github.event.inputs.CCM }}
      UNICODE_BYPASS: ${{ github.event.inputs.UNICODE_BYPASS }}
      SCHED_HMBIRD: ${{ github.event.inputs.SCHED_HMBIRD }}
      DROID_SPACES: ${{ github.event.inputs.DROID_SPACES }}
      RE_KERNEL: ${{ github.event.inputs.RE_KERNEL }}
      SUSFS_DEV: ${{ github.event.inputs.SUSFS_DEV }}
      SPACE_NOCLEAN: ${{ github.event.inputs.SPACE_NOCLEAN }}
      BUILD_NOCACHE: ${{ github.event.inputs.BUILD_NOCACHE }}
      SUSFS_META: ${{ github.event.inputs.SUSFS_META }}
    secrets: inherit
